version: "2"
services:
  postgres:
    container_name: units-postgres
    image: pyramation/postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./packages:/sql-extensions
      - ./node_modules:/sql-modules
  