#!/bin/bash

# this file requires units.csv, which is generated by units.js

psql units <<EOF
\copy units.unit(name,value,amount,description,type,utf8,func) FROM '/Users/dlynch/code/pg/units/packages/unit/seed/units.csv' DELIMITER ',' CSV
EOF

pg_dump --column-inserts --data-only  --table=units.unit units
